### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by ytalashko** [SimplyScala/scalatest-embedmongo#17]
Hi,

I want to use your library in my job's project. But I can't know, do I have permissions to do so, as far as license information is missing for your project. Could you please add license to this github repo. Thanks!

Best regards,
Yurii.

**Comment by tg44** [comment]
Best issue ever :D
I think it will be MIT or Apache btw.

**Comment by ytalashko** [comment]
Thanks, that's cool!
I'll wait for this update.
