### ISSUE TITLE
Switch mongo logging off

### ISSUE THREAD

**Issue by lderks** [SimplyScala/scalatest-embedmongo#4]
Hi,

I would like to be able to switch all the mongo logging off. At the moment I'm seeing a lot of logging  like:
`
[mongod output] Thu Feb 27 16:57:13 dbexit: really exiting now
[mongod output] Thu Feb 27 16:57:13 [initandlisten] connection accepted from 127.0.0.1:61090 #2 (2 connections now open)
[mongod output] Thu Feb 27 16:57:13 [conn1] end connection 127.0.0.1:61069 (1 connection now open)
[mongod output] Thu Feb 27 16:57:13 [conn2] run command admin.$cmd { shutdown: 1, force: true }
[mongod output] Thu Feb 27 16:57:13 [conn2] terminating, shutdown command received
[mongod output] Thu Feb 27 16:57:13 dbexit: shutdown called
[mongod output] Thu Feb 27 16:57:13 [conn2] shutdown: going to close listening sockets...
[mongod output] Thu Feb 27 16:57:13 [conn2] closing listening socket: 5
[mongod output] Thu Feb 27 16:57:13 [conn2] closing listening socket: 6
[mongod output] Thu Feb 27 16:57:13 [conn2] closing listening socket: 7
[mongod output] Thu Feb 27 16:57:13 [conn2] removing socket file: /tmp/mongodb-61060.sock
[mongod output] Thu Feb 27 16:57:13 [conn2] shutdown: going to flush diaglog...
[mongod output] Thu Feb 27 16:57:13 [conn2] shutdown: going to close sockets...
[mongod output] Thu Feb 27 16:57:13 [conn2] shutdown: waiting for fs preallocator...
[mongod output] Thu Feb 27 16:57:13 [conn2] shutdown: closing all files...
[mongod output] Thu Feb 27 16:57:13 [conn1] Socket recv() errno:9 Bad file descriptor 127.0.0.1:61061
[mongod output] Thu Feb 27 16:57:13 [conn2] closeAllFiles() finished
[mongod output] Thu Feb 27 16:57:13 [conn2] shutdown: removing fs lock...
[mongod output] Thu Feb 27 16:57:13 [conn1] SocketException: remote: 127.0.0.1:61061 error:`

**Comment by tg44** [comment]
if sb want to turn off all the mongodb logging completely;

`Logger mongoLogger = Logger.getLogger( "org.mongodb.driver" );
mongoLogger.setLevel(Level.SEVERE); `

According to: https://stackoverflow.com/a/29481937
