### ISSUE TITLE
Multiple test class using embed mongo address already in use for socket:12345

### ISSUE THREAD

**Issue by MadeInChina** [SimplyScala/scalatest-embedmongo#7]
o]   java.io.IOException: Could not start process: ERROR: listen(): bind() failed errno:48 Address already in use for socket: 0.0.0.0:12345

**Comment by ubourdon** [comment]
Can you precise the condition of this issue ?
You start 2 test suite using embedmongo with the same port ?

**Comment by MadeInChina** [comment]
Yes, testing in parallel way
